FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      cmake \
      g++-12 \
      gfortran-12 \
      git \
      vim \
      lldb-13 \
      hdf5-tools \
      libboost-dev \
      libfftw3-dev \
      libgfortran5 \
      libgmp-dev \
      libhdf5-dev \
      # the single mkl packages containing the core gf64 and seq libs do not contain header files!
      libmkl-dev \
      libopenmpi-dev \
      openmpi-bin \
      openmpi-common \
      openmpi-doc \
      python3-dev \
      libpython3-dev \
      python3-pip

ENV PYTHON_VERSION=3.10 \
    CC=gcc-12 CXX=g++-12

COPY requirements.txt /src/$APPNAME/requirements.txt
RUN pip3 install --no-cache-dir -r /src/$APPNAME/requirements.txt

RUN git clone -b v1.26.2 --depth 1 https://github.com/numpy/numpy.git /src/numpy \
    && cd /src/numpy \
    && git submodule update --init \
    && echo "\n[mkl]" >> site.cfg \
    && echo "mkl_libs = mkl_def, mkl_gf_lp64, mkl_core, mkl_sequential" >> site.cfg \
    && echo "lapack_libs = mkl_def, mkl_gf_lp64, mkl_core, mkl_sequential" >> site.cfg \
    && NPY_BLAS_ORDER=MKL NPY_LAPACK_ORDER=MKL python3 setup.py install

RUN rm -rf /src
